Added 2023 Achievements in career section
COPS-IITBHU/cops-website pull request #152
Opened 2024-01-10 18:07 UTC by Vishalk91-4

![image](https://github.com/COPS-IITBHU/cops-website/assets/116670999/693bf5c9-6528-44d1-817f-36b0dc3f604e)

2024-01-27 20:56 UTC, Vishalk91-4 commented
@king-11

2024-01-28 03:18 UTC, king-11 requested changes

2024-01-28 03:18 UTC, king-11 commented on _data/index/careers.yml
> +    detail: Two students from the club (Ankur Patil, Paarth Agarwal and Yash Raj) got accepted as mentees in <a href = "https://lfx.linuxfoundation.org/tools/mentorship/" target="_blank">LFX Mentorsh
Three*

2024-01-28 03:44 UTC, Vishalk91-4 commented
@king-11, Fixed from *three to *two

2024-01-28 03:45 UTC, king-11 approved these changes

2024-01-28 03:45 UTC, merged