Dropdown menu background fix
COPS-IITBHU/cops-website pull request #89
Opened 2020-03-15 15:24 UTC by subodhk01

2020-03-15 15:25 UTC, subodhk01 commented
issue #72

2020-03-17 18:57 UTC, subodhk01 commented
@shivanshs9

2020-04-18 18:51 UTC, shivanshs9 requested changes

2020-04-18 18:51 UTC, shivanshs9 commented on static/css/dropdown-menu.css
> +    box-shadow: 0px 0px 9px 2px rgb(73, 73, 73);
Can you lighten the shadow a bit? Right now, it looks quite a lot raise in light theme on white background

2020-04-19 05:25 UTC, shivanshs9 requested changes
If you'll check the Inspect element, you'll notice the dropdown-menu has two CSS styles applied on it, one by your new CSS file and the other by the existing SCSS. Doesn't make sense to apply style on one element by 2 files, especially since that CSS code has **-webkit-box-shadow** with different value and you have **box-shadow** only. In some earlier browsers, the older value will be applied leading to confusion.
Also I suggest you to just use background and border-radius only and let the box-shadow be the same.

2020-04-19 13:29 UTC, shivanshs9 approved these changes
LGTM!

2020-04-19 13:29 UTC, merged